--[[

COPYRIGHT 2021-PRESENT NoahBrahim (noahalhandy.com) - ALL RIGHTS RESERVED.

THIS SCRIPT IS ALLOWED TO BE MODIFIED TO SUPPORT DIFFERENT COMMANDS OR KEYBINDS TO TRIGGER THE SCRIPT.
DO NOT DISTRIBUTE THIS SOFTWARE WITHOUT STRICT PERMISSION. THIS IS DUE TO THE AMMOUNT OF WORK PUT INTO 
THIS PROJECT. THANK YOU 
- NOAH BRAHIM

]]--





--[[

COPYRIGHT 2021-PRESENT NoahBrahim (noahalhandy.com) - ALL RIGHTS RESERVED.

THIS SCRIPT IS ALLOWED TO BE MODIFIED TO SUPPORT DIFFERENT COMMANDS OR KEYBINDS TO TRIGGER THE SCRIPT.
DO NOT DISTRIBUTE THIS SOFTWARE WITHOUT STRICT PERMISSION. THIS IS DUE TO THE AMMOUNT OF WORK PUT INTO 
THIS PROJECT. THANK YOU 
- NOAH BRAHIM

]]--